### ISSUE TITLE
Engine options'a eklemeler

### ISSUE THREAD

**Issue by SelimAbidin** [eyupinan/grafikMotoru#1]
frameRate  : number "şimdilik bir fonksiyonu olmasına gerek yok"
autoRender : boolean " false ise auto render etmeyecek. dışarıdan render edilmeyi bekleyecek"
backgroundColor : string | int  " background rengini belirleyecek."

**Comment by eyupinan** [comment]
dışarıdan render fonksiyonunun çağırılması işe yaramıyor çünkü bir kez çağırmış olsanızda frame update edildiğinde autoRender kapalı olduğundan görüntü yeni frame'e eklenmiyor

**Comment by SelimAbidin** [comment]
Eklemeler, Engine'in constructor'ına verilmesi gerekiyor.

**Comment by eyupinan** [comment]
parametrelerin alınma şekli değişti
